#!/bin/bash

bootstrap-consul()
{
    docker run -d --label snth --name consul1 -h consul1 progrium/consul -server -bootstrap-expect 3
    JOIN_IP="$(docker inspect -f '{{.NetworkSettings.IPAddress}}' consul1)"
    docker run -d --label snth --name consul2 -h consul2 progrium/consul -server -join $JOIN_IP
    docker run -d --label snth --name consul3 -h consul3 progrium/consul -server -join $JOIN_IP
}

swarm-create-master()
{
    JOIN_IP="$(docker inspect -f '{{.NetworkSettings.IPAddress}}' consul1)"
    DH='127.0.0.1'
    docker run \
        -d \
        -p 4001:2375 \
        swarm manage \
        --advertise=$DH:4001 \
        consul://$JOIN_IP:8500/nodes
}

swarm-create-slaves()
{
    JOIN_IP="$(docker inspect -f '{{.NetworkSettings.IPAddress}}' consul1)"
    for i in {1..3}; do
        DH='127.0.0.1'
        docker run \
            -d \
            -p 300$i:2375 \
            swarm join \
            --advertise=$DH:300$i consul://$JOIN_IP:8500/nodes
    done
}

#bootstrap-consul
